version: '3.3'

services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - 8083:8083 # Admin interface port
      - 8086:8086 # HTTP API port
  grafana:
    image: grafana/grafana:5.0.4
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3333:3000

volumes:
  influxdb-data:
    driver: local
  grafana-data:
    driver: local
